---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamate-postgres
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teslamate-postgres
  template:
    metadata:
      labels:
        app: teslamate-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: teslamate
            - name: POSTGRES_USER
              value: teslamate
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: teslamate-postgres-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: teslamate-postgres-data