---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: peppermint-db-backup
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: peppermint-db-backup-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_HOST: postgres-rw.database.svc.cluster.local
        DB_USER: "{{ .POSTGRES_USER }}"
        DB_PASS: "{{ .POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: peppermint
    - extract:
        key: cloudnative-pg
