---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:

        # database
        DATABASE_NAME: "{{ .DATABASE_NAME }}"
        DATABASE_USER: "{{ .DATABASE_USER }}"
        DATABASE_PASS: "{{ .DATABASE_PASS }}"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"

        # init database
        INIT_POSTGRES_DBNAME: "{{ .DATABASE_NAME }}"
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .DATABASE_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
  dataFrom:
    - extract:
        key: teslamate
    - extract:
        key: cloudnative-pg
