---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
