---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: media
spec:
  interval: 15m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chartRef:
    kind: OCIRepository
    name: sabnzbd

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    podSecurityContext:
      runAsUser: 1026
      runAsGroup: 65537
      fsGroup: 65537
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: DoesNotExist
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist

    controllers:
      sabnzbd:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.3@sha256:ecb57bd6257fbfbd9aee70d8ef3df8814b7270ae793fd1f44219ae73cacd519a
            env:
              TZ: "America/Chicago"
              SABNZBD__PORT: &port 80
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.media,
                sabnzbd.media.svc,
                sabnzbd.media.svc.cluster,
                sabnzbd.media.svc.cluster.local,
                sabnzbd.kalde.in
            resources:
              requests:
                memory: 1000Mi
                cpu: "1.5"
              limits:
                memory: 2000Mi
                cpu: "3"

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-v3
      downloads:
        enabled: true
        type: nfs
        server: "192.168.10.3"
        path: /volume1/downloads/complete
        globalMounts:
          - path: /downloads
      incomplete:
        enabled: true
        type: nfs
        server: "192.168.10.3"
        path: /volume1/downloads/incomplete
        globalMounts:
          - path: /incomplete-downloads
      backup:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/backup/sabnzbd
        globalMounts:
          - path: /backup
