---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_USER: "{{ .db_username }}"
        POSTGRES_DB: "{{ .db_name }}"
        POSTGRESS_PASSWORD: "{{ .db_password }}"

        INIT_POSTGRES_DBNAME: "{{ .db_name }}"
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .db_username }}"
        INIT_POSTGRES_PASS: "{{ .db_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: cloudnative-pg
