# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:qEp5uy8nZeOr9VYm01XkI224sMSKI+C0XvYuRkzKsJmaZ9WYUe9Xtw==,iv:qL2mMLRX91aCAD6IkcRD53ucW/uV9vwLdCNKypqf6ws=,tag:Ai9z0zpvto/KZwQPzDMiQQ==,type:str]
sops:
  age:
    - recipient: age1rpavzet35zr3pgqcvz9emvgmuzlc5w9w2cjwl86arr406c6hlaqqszqt2u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd2YzMitFU3RTUTkwc2hs
        aTY1THBPNUJodUhZUmRJTW81UzZ2Q2F4MFhrCnh4UUJZVXFpdDhKUVJrMlFjMkE2
        YkYxWFpmY3ZqcnR6eTRHT3NMNHhERUEKLS0tICs2RHcvZ3ZHNVdmUDlqNS85a3No
        NHd0alFiSkp2UndmYkUvcUdrQURCdnMKc9xW+Qlwba4Ukt+EV88EuYkPxpm+xRgc
        xJTIa9uKeKD16xD8fjBe3g2wMBic9VVnb4fhBzXM95wBP8B9DP7wIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-17T04:13:22Z"
  mac: ENC[AES256_GCM,data:/IxwGqoEGGCIEDwKZfo5zt211yu8sbjHCEYp3aKKcYqsrz92O6hNIi0DirPSrcwtXOklMmKi52AIIgmz+qf+TR69QEHP5FCSQHcPsczH1tPCorIqyQI6WY2ofhP2e9XQP9hmaTIwOnSCa6BCR968f3sGdTMqPqoJiBTmr6f+W8A=,iv:ZHqMKMLVMDkLOGepd03hSMppq+6cdMM7UluNPMD/2vY=,tag:SJ52XOGsh6KsAbX3MOuPgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
