# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1rpavzet35zr3pgqcvz9emvgmuzlc5w9w2cjwl86arr406c6hlaqqszqt2u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcFpPUmtVOGVUN2JPWmVE
        bUg0VGpDM2JMRTF0WlIydkR1TVFFK2tOamlVCi9VdnJOM3RYWmxEemJrKzhUcmh2
        NThrYW1GK0dGNTkvaUptVU5GdytXbW8KLS0tIDNic1N4N1ZIRXljYWR5bm5aVk1X
        Yk9HQmM3ZkZYcHkyK1RSaG1SYzN4WFEKxoAJHrwM36G30gGQdnB5hUMKd/HZI7SO
        BpXRP0hyYz06owmLtKcsfsTlBBM7GNk3SEsbZlEGi9oznESjJIw2ZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-17T04:13:22Z"
  mac: ENC[AES256_GCM,data:CSAQOYMeuj3AFEVdf31SPAAdtWNFlC1M+9KaWcchTp+yLnUPRTFstR1ZkjfE+KIKsTabqmm6T0Zp1WRQDBWAvAT8riurp628k5h5EX8SD+FjdP3gHl3NZDvEyJ5hHm5p/Gsyou4/+mxHRajihJ4ipD3M3G0s0d1j4ET4YYjMpJc=,iv:Q/xOUvwYu5G61GJmJG+Zo9l23N6YbZS2MHMNmikGa5g=,tag:Dz3r1EtiT6plDzKcokOuTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
