---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miniflux-db-backup
  namespace: default
spec:
  interval: "30m"
  chartRef:
    kind: OCIRepository
    name: miniflux-db-backup
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      backup:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
        containers:
          app:
            image:
              repository: casmith/pgsqldump
              tag: v0.3.1
            env:
              DB_NAME: miniflux
              FLAGS: "-Fc"
            envFrom:
              - secretRef:
                  name: miniflux-db-backup-secret
            restartPolicy: OnFailure
    service:
      backup:
        enabled: false
    persistence:
      backup:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/db-backup/miniflux
        globalMounts:
          - path: /pgsqldump
