---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app consolewiki
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: consolewiki
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      consolewiki:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: redimp/otterwiki
              tag: 2.14
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                cpu: "1"
                memory: 1000Mi
    service:
      app:
        ports:
          http:
            port: &port 80
    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http
    route:
      app:
        hostnames: ["consolewiki.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: consolewiki-data-v1
        globalMounts:
          - path: /app-data
      backup:
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/backup/consolewiki
        globalMounts:
          - path: /backup
