---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: peppermint
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: peppermint-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DB_USERNAME: "{{ .POSTGRES_USER }}"
        DB_PASSWORD: "{{ .POSTGRES_PASS }}"
        DB_HOST: postgres-rw.database.svc.cluster.local
  dataFrom:
    - extract:
        key: peppermint
