---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app peppermint
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: peppermint
  interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      peppermint:
        containers:
          app:
            image:
              repository: pepperlabs/peppermint
              tag: latest
            env:
              BASE_URL: https://peppermint.kalde.in
              API_URL: https://peppermint.kalde.in
              SECRET: whatever4peppermint
            envFrom:
              - secretRef:
                  name: peppermint-secret
            resources:
              requests:
                memory: 500Mi
                cpu: "1.5"
              limits:
                memory: 500Mi
                cpu: "3"
        pod:
          nodeSelector:
            kubernetes.io/arch: amd64
    service:
      peppermint:
        ports:
          http:
            port: 3000
    route:
      peppermint:
        hostnames: ["{{ .Release.Name }}.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: peppermint
                port: 3000
