---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akaunting-storage-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
