---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./consolewiki/ks.yaml
  - ./dailytrace/ks.yaml
  - ./echo/ks.yaml
  - ./linkding/ks.yaml
  - ./longhorn/ks.yaml
  - ./miniflux/ks.yaml
  - ./peppermint/ks.yaml
  - ./sync-todoist-to-habitica/ks.yaml
  - ./wallabag/ks.yaml
