---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-ngx-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App

        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRETKEY }}"

        PAPERLESS_DBNAME: paperless
        PAPERLESS_DBUSER: "{{ .POSTGRES_USER }}"
        PAPERLESS_DBPASS: "{{ .POSTGRES_PASS }}"
        PAPERLESS_DBHOST: postgres-rw.database.svc.cluster.local
        PAPERLESS_DBENGINE: postgres

        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_MAIL: "{{ .PAPERLESS_ADMIN_MAIL }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: paperless
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
  dataFrom:
    - extract:
        key: paperless-ngx
    - extract:
        key: cloudnative-pg
