---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 15m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chartRef:
    kind: OCIRepository
    name: radarr

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    initContainers:
      - name: 01-init-db
        image: ghcr.io/onedr0p/postgres-init:17.4
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: radarr-secret

    controllers:
      radarr:
        pod:
          securityContext:
            runAsUser: 1026
            runAsGroup: 65537
            fsGroup: 65537
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 100
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: rolling@sha256:4fa8fc7dcf3b38dbed279125330a8b9bd7be6e68e317e685089d3b03774aeeab
            env:
              TZ: ${TIMEZONE}
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 80
              RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.kalde.in"
              RADARR__LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: radarr-secret
            resources:
              requests:
                memory: 500Mi
                cpu: "1.5"
              limits:
                memory: 500Mi
                cpu: "3"

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.kalde.in", "radarr.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/radarr
        globalMounts:
          - path: /config
      downloads:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/downloads/complete/movies
        globalMounts:
          - path: /downloads
      movies:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume2/share/videos/movies
        globalMounts:
          - path: /movies
