---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate-db-backup
  namespace: media
spec:
  interval: "30m"
  chartRef:
    kind: OCIRepository
    name: teslamate-db-backup
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      teslamate-db-backup:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
        pod:
          restartPolicy: OnFailure
        containers:
          app:
            image:
              repository: casmith/pgsqldump
              tag: v0.3.1
              pullPolicy: IfNotPresent
            env:
              DB_NAME: teslamate
              FLAGS: "-Fc"
            envFrom:
              - secretRef:
                  name: teslamate-db-backup-secret

    persistence:
      backup:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/db-backup/teslamate
        globalMounts:
          - path: /pgsqldump
