---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate-mosquitto
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: teslamate-mosquitto
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      teslamate-mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: eclipse-mosquitto
              tag: 2
            command:
              - mosquitto
            args:
              - -c
              - "/mosquitto-no-auth.conf"
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 750Mi

    service:
      app:
        ports:
          http:
            port: &port 1883

    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http

    persistence:
      config:
        enabled: true
        existingClaim: teslamate-mosquitto-config-v1
        globalMounts:
          - path: /mosquitto/config
      data:
        enabled: true
        existingClaim: teslamate-mosquitto-data-v1
        globalMounts:
          - path: /mosquitto/data
