---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-mosquitto-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  storageClassName: longhorn
