---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-datastore-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
