---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate-grafana
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: teslamate-grafana
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      teslamate-grafana:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: teslamate/grafana
              tag: 2.1
            env:
              DATABASE_HOST: postgres-rw.database.svc.cluster.local
            envFrom:
              - secretRef:
                  name: teslamate-secret
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 750Mi

    service:
      app:
        ports:
          http:
            port: &port 3000

    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http



    route:
      app:
        hostnames: ["tesla-grafana.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        enabled: true
        existingClaim: teslamate-grafana-v1
        globalMounts:
          - path: /var/lib/grafana
