---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sync-todoist-to-habitica
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: sync-todoist-to-habitica
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      backup:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          startingDeadlineSeconds: 60
          schedule: "*/5 * * * *"
        containers:
          app:
            image:
              repository: casmith/sync-todoist-to-habitica
              tag: 2025.09.04.4d9703cb
            env:
              TODOIST_UNMATCHED_DAILY_TASK: Todoist Daily
              CONFIG_DIR: /data
            envFrom:
              - secretRef:
                  name: sync-todoist-to-habitica-secret
            restartPolicy: Never
    service:
      backup:
        enabled: false
    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/sync-todoist-to-habitica
        globalMounts:
          - path: /data
