---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: longhorn-ui
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      longhorn-ui:
        replicas: 3
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: longhornio/longhorn-ui
              tag: v1.9.1
            env:
              LONGHORN_MANAGER_IP: "http://longhorn-backend:9500"
            resources:
              requests:
                memory: 128Mi
                cpu: 100m
              limits:
                memory: 256Mi
                cpu: 500m
    service:
      app:
        ports:
          http:
            port: &port 8000
    route:
      app:
        hostnames: ["longhorn.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: longhorn-ui-app
                namespace: longhorn-system
                port: *port
