---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: longhorn-ui
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      longhorn-ui:
        replicas: 3
        strategy: RollingUpdate
        pod:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values: ["longhorn-ui"]
                    topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: longhornio/longhorn-ui
              tag: v1.9.1
            env:
              LONGHORN_MANAGER_IP: "http://longhorn-backend:9500"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                    httpHeaders:
                      - name: Accept
                        value: text/html
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                    httpHeaders:
                      - name: Accept
                        value: text/html
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                    httpHeaders:
                      - name: Accept
                        value: text/html
                  initialDelaySeconds: 0
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
            resources:
              requests:
                memory: 128Mi
                cpu: 100m
              limits:
                memory: 256Mi
                cpu: 500m
    service:
      app:
        type: ClusterIP
        sessionAffinity: ClientIP
        sessionAffinityConfig:
          clientIP:
            timeoutSeconds: 3600
        ports:
          http:
            port: &port 8000
