---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: longhorn-ui
      app.kubernetes.io/instance: longhorn-ui
