---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-monitor
  namespace: longhorn-system
data:
  monitor.sh: |
    #!/bin/bash
    echo "Starting Longhorn UI monitoring..."
    while true; do
      timestamp=$(date '+%Y-%m-%d %H:%M:%S')
      
      # Check pod status
      ready_pods=$(kubectl get pods -n longhorn-system -l app.kubernetes.io/name=longhorn-ui --no-headers | grep -c "Running.*1/1")
      total_pods=$(kubectl get pods -n longhorn-system -l app.kubernetes.io/name=longhorn-ui --no-headers | wc -l)
      
      # Check service endpoints
      endpoints=$(kubectl get endpoints -n longhorn-system longhorn-ui -o jsonpath='{.subsets[0].addresses}' | jq length 2>/dev/null || echo "0")
      
      echo "[$timestamp] Ready pods: $ready_pods/$total_pods, Service endpoints: $endpoints"
      
      # Check for recent pod restarts
      restarts=$(kubectl get pods -n longhorn-system -l app.kubernetes.io/name=longhorn-ui -o jsonpath='{.items[*].status.containerStatuses[0].restartCount}' | tr ' ' '\n' | awk '{sum+=$1} END {print sum}')
      
      if [ "$ready_pods" -lt 2 ]; then
        echo "[$timestamp] WARNING: Less than 2 ready pods! This could cause 503 errors."
        kubectl get pods -n longhorn-system -l app.kubernetes.io/name=longhorn-ui
      fi
      
      sleep 30
    done
