---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dailytrace-frontend
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/dailytrace/frontend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: cluster-apps-dailytrace-backend

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dailytrace-backend
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/dailytrace/backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dailytrace-db
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/dailytrace/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dailytrace-db-backup
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/dailytrace/database-backup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
