---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lidarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        LIDARR__API_KEY: "{{ .LIDARR__API_KEY }}"
        LIDARR__POSTGRES__HOST: &dbHost postgres-rw.database.svc.cluster.local
        LIDARR__POSTGRES__PORT: "5432"
        LIDARR__POSTGRES__USER: &dbUser "{{ .LIDARR__POSTGRES_USER }}"
        LIDARR__POSTGRES__PASSWORD: &dbPass "{{ .LIDARR__POSTGRES_PASSWORD }}"
        LIDARR__POSTGRES__MAINDB: lidarr_main
        LIDARR__POSTGRES__LOGDB: lidarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: lidarr_main lidarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lidarr
    - extract:
        key: cloudnative-pg
