---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wallabag-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:

        # database
        SYMFONY__ENV__DATABASE_CHARSET: utf8
        SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
        SYMFONY__ENV__DATABASE_HOST: postgres-rw.database.svc.cluster.local
        SYMFONY__ENV__DATABASE_NAME: "{{ .db_name }}"
        SYMFONY__ENV__DATABASE_PASSWORD: "{{ .db_password }}"
        SYMFONY__ENV__DATABASE_PORT: "5432"
        SYMFONY__ENV__DATABASE_USER: "{{ .db_username }}"

        # mailer
        SYMFONY__ENV__MAILER_HOST: "127.0.0.1"
        SYMFONY__ENV__MAILER_PASSWORD: ""
        SYMFONY__ENV__MAILER_USER: ""
        SYMFONY__ENV__SERVER_NAME: ""

        # init database
        INIT_POSTGRES_DBNAME: "{{ .db_name }}"
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .db_username }}"
        INIT_POSTGRES_PASS: "{{ .db_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
  dataFrom:
    - extract:
        key: wallabag
    - extract:
        key: cloudnative-pg
