---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dailytrace-backend
  namespace: default
spec:
  dependsOn:
    - name: dailytrace-db
      namespace: default
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: dailytrace-backend
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      backend:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: casmith/dailytrace-api
              tag: 2025.09.14.0e4e195a
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 750Mi
            envFrom:
              - secretRef:
                  name: dailytrace-secret
    service:
      backend:
        ports:
          http:
            port: 8081
    serviceMonitor:
      backend:
        enabled: true
        endpoints:
          - port: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    route:
      backend:
        hostnames: ["dailytrace.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: "/api"
            backendRefs:
              - identifier: backend
                port: 8081
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
